/**
 * Signing in for real, against a local stand-in for AgentX SSO (fake-sso.ts).
 *
 * 1. The keys service refuses the first key with the SSO console's HTTP 424:
 *    the app must stop at the key gate — no other provider, no "later" — and
 *    stay there through a retry that is refused again; once the console grants
 *    a model, "Try again" lets the person in.
 * 2. The administrator then renames the person in the console: signing in
 *    again must land in the same account home, with everything in it, instead
 *    of a new empty one (what an update that "wiped everything" looked like).
 *
 * The boot is held before the renderer has read `display.language`, so the
 * gate speaks the default locale (Vietnamese) — the assertions do too.
 */

import fs from 'node:fs'
import path from 'node:path'

import type { ElectronApplication, Page } from '@playwright/test'

import { FAKE_SSO_CLIENT_ID, FAKE_SSO_REALM, type FakeSso, startFakeSso } from './fake-sso'
import { buildAppEnv, createSandbox, launchDesktop, type Sandbox } from './fixtures'
import { allowErrorBanners, expect, test } from './test'

const GATE_TITLE = 'Chưa cấp được key AgentX AI'
const NO_MODELS = 'Tài khoản của bạn chưa được gán model nào đang hoạt động trên AgentX AI Gateway.'
const CONTACT_SUPPORT = 'Vui lòng liên hệ bộ phận hỗ trợ AgentX'
const RETRY = 'Thử lại'
const SIGN_IN = /Đăng nhập bằng AgentX|Sign in with AgentX/

function writeSsoConfig(sandbox: Sandbox, sso: FakeSso): void {
  fs.writeFileSync(
    path.join(sandbox.hermesHome, 'config.yaml'),
    [
      '# Auto-generated by agentx-key-gate.spec.ts — signs in against fake-sso.ts',
      'dashboard:',
      '  oauth:',
      '    keycloak:',
      `      base_url: ${sso.url}`,
      `      realm: ${FAKE_SSO_REALM}`,
      `      client_id: ${FAKE_SSO_CLIENT_ID}`,
      'accounts:',
      '  second_brain:',
      `    base_url: ${sso.url}`,
      'display:',
      '  language: en',
      'security:',
      '  tirith_enabled: false',
      ''
    ].join('\n'),
    'utf8'
  )
}

/**
 * The desktop opens the authorize URL in a browser. A browser with a live SSO
 * session is redirected straight back to the app's loopback listener; following
 * that redirect from the main process is the same thing, minus the window.
 */
async function routeSignInThroughFetch(app: ElectronApplication): Promise<void> {
  await app.evaluate(({ shell }) => {
    shell.openExternal = async (url: string) => {
      await fetch(url, { redirect: 'follow' }).catch(() => undefined)
    }
  })
}

async function signIn(page: Page): Promise<void> {
  const button = page.getByRole('button', { name: SIGN_IN })

  await button.waitFor({ state: 'visible', timeout: 180_000 })
  await button.click()
}

/** The account homes on disk, by slug. */
function accountHomes(sandbox: Sandbox): string[] {
  try {
    return fs.readdirSync(path.join(sandbox.hermesHome, 'accounts')).sort()
  } catch {
    return []
  }
}

async function waitForComposer(page: Page): Promise<void> {
  await page.waitForSelector('[contenteditable="true"]', { state: 'visible', timeout: 180_000 })
  await expect(page.locator('#agentx-key-gate-title')).toHaveCount(0)
}

test('a refused AgentX key holds the app at the key gate until it is issued, and a rename keeps the home', async () => {
  test.setTimeout(600_000)
  // The gate is an error by design: its reason line is role="alert".
  allowErrorBanners()

  const sso = await startFakeSso({ name: 'Lê Trung Kiên' })
  const sandbox = createSandbox('key-gate')
  let app: ElectronApplication | undefined

  try {
    writeSsoConfig(sandbox, sso)

    // The realm through the environment as well: once signed in, the backend
    // runs in the account's own home, whose config.yaml is not this one.
    const launched = await launchDesktop(
      buildAppEnv(sandbox, {
        AGENTX_DASHBOARD_KEYCLOAK_BASE_URL: sso.url,
        AGENTX_DASHBOARD_KEYCLOAK_CLIENT_ID: FAKE_SSO_CLIENT_ID,
        AGENTX_DASHBOARD_KEYCLOAK_REALM: FAKE_SSO_REALM
      })
    )

    app = launched.app
    const { page } = launched

    await routeSignInThroughFetch(app)
    await signIn(page)

    // ── 1. The key is refused: the app stops at the gate ───────────────
    const gate = page.getByRole('alertdialog')

    await expect(gate).toBeVisible({ timeout: 240_000 })
    await expect(gate.getByText(GATE_TITLE)).toBeVisible()
    await expect(gate.getByText(NO_MODELS)).toBeVisible()
    await expect(gate.getByText(CONTACT_SUPPORT, { exact: false })).toBeVisible()
    await expect(gate.getByText('Tài khoản: kien.test@astralx.com.vn', { exact: true })).toBeVisible()
    // Nothing behind it has started, and nothing on it leads around the key.
    await expect(page.locator('[contenteditable="true"]')).toHaveCount(0)
    await expect(page.getByText('Chọn nhà cung cấp khác')).toHaveCount(0)
    await expect(page.getByText('Để sau tôi chọn nhà cung cấp')).toHaveCount(0)
    await expect(page.getByText('Tôi đã có API key')).toHaveCount(0)

    const [home] = accountHomes(sandbox)

    expect(accountHomes(sandbox)).toHaveLength(1)
    expect(fs.readFileSync(path.join(sandbox.hermesHome, 'accounts', home, '.env'), 'utf8')).not.toContain(
      'sk-fake-sso'
    )

    // Still refused: still held, one more request.
    const asked = sso.keyRequests()

    await gate.getByRole('button', { exact: true, name: RETRY }).click()
    await expect.poll(() => sso.keyRequests(), { timeout: 60_000 }).toBe(asked + 1)
    await expect(gate.getByRole('button', { exact: true, name: RETRY })).toBeEnabled({ timeout: 60_000 })
    await expect(gate.getByText(NO_MODELS)).toBeVisible()

    // ── 2. The console grants a model: "Try again" lets the person in ──
    sso.setKeys('issue')
    await gate.getByRole('button', { exact: true, name: RETRY }).click()
    await waitForComposer(page)

    const accountHome = path.join(sandbox.hermesHome, 'accounts', home)

    expect(fs.readFileSync(path.join(accountHome, '.env'), 'utf8')).toContain('sk-fake-sso-0123456789abcdef')

    // Something only this person's home holds.
    const probe = path.join(accountHome, 'memories', 'rename-probe.md')

    fs.mkdirSync(path.dirname(probe), { recursive: true })
    fs.writeFileSync(probe, 'still here after the rename', 'utf8')

    // ── 3. Renamed in the console, signing in again keeps the home ─────
    // What Settings → Account → Sign out does (store/account.ts signOutKeycloak).
    await page.evaluate(async () => {
      const desktop = (
        window as unknown as {
          agentxDesktop: { keycloak: { signOut(): Promise<unknown> }; resetBootstrap(): Promise<unknown> }
        }
      ).agentxDesktop

      await desktop.keycloak.signOut()
      await desktop.resetBootstrap()
    })
    sso.setName('Kiên Lê')
    await page.reload()
    await signIn(page)
    await waitForComposer(page)

    expect(accountHomes(sandbox)).toEqual([home])
    expect(fs.readFileSync(probe, 'utf8')).toBe('still here after the rename')

    const log = fs.readFileSync(path.join(sandbox.hermesHome, 'logs', 'desktop.log'), 'utf8')

    expect(log).toContain(`the account already lives in "${home}"`)
  } finally {
    await app?.close().catch(() => undefined)
    await sso.close()
    sandbox.cleanup()
  }
})
